name: Auto Checkin

on:
  schedule:
    - cron: '0 2 * * *' # 每天10:00运行

jobs:
  auto-checkin-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # 使用最新的Python 3版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 如果你的脚本需要特定的环境变量，请在这里设置
      - name: Run the checkin script
        env:
          COOKIES: ${{ secrets.COOKIES }}
          TELEID: ${{ secrets.TELEID }}
          TELETOKEN: ${{ secrets.TELETOKEN }}
          SCKEY: ${{ secrets.SCKEY }}
          QQKEY: ${{ secrets.QQKEY }}
          PPKEY: ${{ secrets.PPKEY }}
        run: |
          python main.py $COOKIES $TELEID $TELETOKEN $SCKEY $QQKEY $PPKEY
          python /qinglong/qinglong.py
